node {
    // Clean workspace before doing anything
    deleteDir()
//    sh "echo 'Please check the Blue Ocean Symbol for piepline'"
//    sh "echo 'Click the Sun Symbol for phases of pipeline'"

    try {
        stage ('Clone') {
            checkout scm
        }
        stage ('Build') {
            sh "echo 'shell scripts to build project...'"
        }
        stage ('Tests') {
            parallel 'static': {
                sh "echo 'shell scripts to run static tests...(Sonar)'"
            },
            'unit': {
                sh "echo 'shell scripts to run unit tests...'"
            },
            'integration': {
                sh "echo 'shell scripts to run integration tests...'"
            }
        }
        stage ('Deploy') {
            sh "echo 'shell scripts to deploy to server...'"
        }
	sh "echo 'PLEASE CHECK THE BLUE OCEAN SYMBOL ON THE LEFT'"
	sh "echo 'CLICK THE SUN SYMBOL FOR PIPELINE STRUCTURE VIEW'"

    } catch (err) {
        currentBuild.result = 'FAILED'
        throw err
    }
}
